import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.tsx';
import './index.css';
import { Amplify } from 'aws-amplify';
// Import the brand-new outputs file generated by Gen 2
import outputs from '../amplify_outputs.json';

import { AppProvider } from './AppContext.tsx';

// Configure Amplify immediately before rendering anything else
Amplify.configure(outputs);

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <AppProvider>
      <App />
    </AppProvider>
  </React.StrictMode>
);
